query getContactDetails($_id: ObjectId){
  trainingPasss(query: {
    contact: {
      _id: $_id
    }
    isActive: true
  }) {
    _id
    type
    size
    capacity
    duration
    activation
    createdAt
  }
  payments(query: {
    contact: {
      _id: $_id
    },
    pass: {
      isActive: true
    }
    type: "units"
  }) {
    _id
    pass {
      _id
    }
    amount
    date
  }
}