#import "../../payments-block/payment-form/pass-select/pass.gql"
#import "../../payments-block/payment-form/pass-select/payment.gql"

query getContactDetails($_id: ObjectId){
  trainingPasss(query: {
    contact: {
      _id: $_id
    }
    isActive: true
  }) {
    ...paymentPass
  }
  payments(query: {
    contact: {
      _id: $_id
    },
    type: "units"
  }) {
    ...passPayment
  }
}