query getTrainingPasses{
  trainingPasss(query: { isActive: true }) {
    _id
    contact {
      _id
      firstName
      lastName
    }
    type
    size
    capacity
    duration
    activation
    createdAt
    price
    isActive
  }
  payments(query: { type: "units", pass: { isActive: true } }) {
    _id
    amount
    date
    gym {
      _id
      name
    }
    pass {
      _id
    }
  }
}