export const CREATE_RECORD = 'schedule/CREATE_RECORD'
export const MOVE_RECORD = 'schedule/MOVE_RECORD'
export const OPEN_CREATE_RECORD_DIALOG = 'schedule/OPEN_CREATE_RECORD_DIALOG'
export const OPEN_UPDATE_RECORD_DIALOG = 'schedule/OPEN_UPDATE_RECORD_DIALOG'
export const CLOSE_RECORD_DIALOG = 'schedule/CLOSE_RECORD_DIALOG'

export default {
  CREATE_RECORD,
  MOVE_RECORD,
  OPEN_CREATE_RECORD_DIALOG,
  OPEN_UPDATE_RECORD_DIALOG,
  CLOSE_RECORD_DIALOG,
}
