export const OPEN_CREATE_TRAINING_DIALOG = 'schedule/page/OPEN_CREATE_TRAINING_DIALOG'
export const OPEN_UPDATE_TRAINING_DIALOG = 'schedule/page/OPEN_UPDATE_TRAINING_DIALOG'

export const SET_CURRENT_DATE = 'schedule/page/SET_CURRENT_DATE'
export const SET_CURRENT_GYM = 'schedule/page/SET_CURRENT_GYM'
export const TOGGLE_OPENED_TRAINERS = 'schedule/page/TOGGLE_OPENED_TRAINERS'

export default {
  OPEN_CREATE_TRAINING_DIALOG,
  OPEN_UPDATE_TRAINING_DIALOG,
  SET_CURRENT_DATE,
  SET_CURRENT_GYM,
  TOGGLE_OPENED_TRAINERS,
}
