  mutation closeTrainingRecords ($date: DateTime, $gym: ObjectId, $_id: ObjectId, $data: TrainingRecordUpdateInput!, $balance: Int!) {
    updateManyTrainingRecords(query: {
      contact: {
        _id: $_id
      },
      training: {
        date: $date,
        gym: {
          _id: $gym
        }
      }
    }, set: $data) {
      modifiedCount
    }
    updateOneClient(query: {
      _id: $_id
    }, set: {
      balance: $balance
      visitedAt: $date
    }) {
      _id
      balance
    }
  }