  mutation closeTrainingRecords ($date: DateTime, $gym: ObjectId, $_id: ObjectId, $status: String!, $balance: Int!) {
    updateManyTrainingRecords(query: {
      contact: {
        _id: $_id
      },
      training: {
        date: $date,
        gym: {
          _id: $gym
        }
      }
    }, set: {
      status: $status
    }) {
      modifiedCount
    }
  updateManyCheckPositions(query: {
    contact: {
      _id: $_id
    },
    date: $date,
    gym: {
      _id: $gym
    }
  }, set: {
    status: "RESOLVED"
  }) {
    modifiedCount
  }
  updateManyPayments(query: {
    contact: {
      _id: $_id
    },
    date: $date,
    gym: {
      _id: $gym
    }
  }, set: {
    status: "RESOLVED"
  }) {
    modifiedCount
  }
    updateOneClient(query: {
      _id: $_id
    }, set: {
      balance: $balance
      visitedAt: $date
    }) {
      _id
      balance
    }
  }