query getClients(
  $sortBy: ClientSortByInput!,
  $minVisitedAt: DateTime,
  $maxVisitedAt: DateTime,
  $minBirthday: DateTime,
  $maxBirthday: DateTime,
  $maxBalance: Int
  )
{
  clients(
    limit: 100,
    sortBy: $sortBy,
    query: {
      visitedAt_gte: $minVisitedAt,
      visitedAt_lt: $maxVisitedAt,
      birthday_gte: $minBirthday,
      birthday_lt: $maxBirthday,
      balance_lt: $maxBalance,
      firstName_ne: "",
      lastName_ne: ""
    }
  ) {
    _id
    firstName
    lastName
    birthday
    phone
    altPhone
    balance
    communicationType
    specialConditions
    group
    groupRole
    visitedAt
  }
}