query getClients($sortBy: ClientSortByInput!){
  clients(limit: 100, sortBy: $sortBy, query: { firstName_ne: "", lastName_ne: "" }) {
    _id
    firstName
    lastName
    birthday
    phone
    altPhone
    balance
    communicationType
    specialConditions
    group
    groupRole
    visitedAt
  }
}