#import "../../records-block/record-item/record.gql"
#import "../../total-block/record.gql"
#import "../../header/contact.gql"
#import "../../pass-form/contact-suggester/contact.gql"
#import "../../payments-block/payment-item/payment.gql"
#import "../../total-block/payment.gql"

query getContactDetails($date: DateTime, $gym: ObjectId, $_id: ObjectId){
    trainingRecords(query: {
      contact: {
        _id: $_id
      },
      training: {
        date: $date,
        gym: {
          _id: $gym
        }
      }
    }) {
      ...checkRecord
      ...totalServiceRecord
      status
    }
    payments(query: {
      contact: {
        _id: $_id
      },
      date: $date,
      gym: {
        _id: $gym
      }
    }) {
      ...checkPaymentItem
      ...totalCheckPayment
    }
    user(query: { _id: $_id }) {
      ...headerContact
      ...passFormContact
    }
  }