mutation createTrainingPass ($data: TrainingPassInsertInput!) {
  insertOneTrainingPass(data: $data) {
    _id
    contact {
      _id
      fullName
    }
    type
    size
    capacity
    duration
    activation
    createdAt
    isActive
    price
  }
}
