query getContactDetails($date: DateTime, $gym: ObjectId, $_id: ObjectId){
  trainingRecords(query: {
    contact: {
      _id: $_id
    },
    training: {
      date: $date,
      gym: {
        _id: $gym
      }
    }
  }) {
    _id
    resource {
      _id
      startTime
      endTime
    }
    training {
      _id
      type
      name
    }
    status
  }
  checkPositions(query: {
    contact: {
      _id: $_id
    },
    date: $date,
    gym: {
      _id: $gym
    }
  }) {
    _id
    type
    service
    priceType
    priceAmount
    status
  }
  payments(query: {
    contact: {
      _id: $_id
    },
    date: $date,
    gym: {
      _id: $gym
    }
  }) {
    _id
    type
    pass {
      _id
    }
    createdAt
    amount
    destination
    transaction
    status
  }
  client(query: { _id: $_id }) {
    _id
    firstName
    lastName
    balance
  }
}