mutation createCheckPosition ($data: CheckPositionInsertInput!) {
  insertOneCheckPosition(data: $data) {
    _id
    contact {
      _id
    }
    type
    service
    priceType
    priceAmount
    date
    gym {
      _id
    }
  }
}
