query getRecords (
  $minDate: DateTime!,
  $maxDate: DateTime!,
  $trainer: TrainerQueryInput,
  $gym: ObjectId,
  $types: [String]
) {
  trainingRecords(query: {
    training: {
      date_gte: $minDate
      date_lt: $maxDate
      gym: {
        _id: $gym
      }
      type_in: $types
    }
    resource: {
      trainer: $trainer
    }
  }) {
    _id
    training {
      _id
      date
      gym {
        _id
        shortName
      }
      type
    }
    resource {
      startTime
      endTime
      trainer {
        _id
        firstName
        lastName
      }
    }
    contact {
      _id
      firstName
      lastName
    }
  }
}