query getTrainingResource(
  $date: DateTime,
  $time: Int!,
  $resource: ObjectId!
){
    newTraining(query: {
      date: $date
      startTime_lte: $time,
      endTime_gt: $time,
      resource: {
        _id: $resource
      }
    }) {
      _id
      type
      name
      note
      date
      startTime
      endTime
      resource {
        _id
      }
      gym {
        _id
      }
      trainer {
        _id
        color
        avatarSrc
        firstName
        lastName
      }
      # training {
      #   _id
      # }
    }
  trainingRecords(query: {
    training: {
      date: $date
      startTime_lte: $time,
      endTime_gt: $time,
      resource: {
        _id: $resource
      }
    }
  }) {
    _id
    contact {
      _id
      firstName
      lastName
    }
    note
    attendant {
      _id
      firstName
      lastName
    }
    status
  }
}