export const CREATE_TRAINING = 'trainings/CREATE_TRAINING'
export const READ_TRAININGS = 'trainings/READ_TRAININGS'
export const UPDATE_TRAINING = 'trainings/UPDATE_TRAINING'
export const DELETE_TRAINING = 'trainings/DELETE_TRAINING'
export const MOVE_TRAINING = 'trainings/MOVE_TRAINING'

export const READ_TRAININGS_SUCCESS = 'trainings/READ_TRAININGS_SUCCESS'

export default {
  CREATE_TRAINING,
  READ_TRAININGS,
  UPDATE_TRAINING,
  DELETE_TRAINING,
  READ_TRAININGS_SUCCESS,
  MOVE_TRAINING,
}
